version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./src/:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    
networks: 
  default:
    external:
      name: js-proxy-net

  